### ISSUE TITLE
BT::ROSAction::WaitForTick takes up 100% cpu time

### ISSUE THREAD

**Issue by fnivek** [miccol/ROS-Behavior-Tree#17]
The thread is not put to sleep in the while loop. Consider something like the following.

```C++        
do
{
      node_result = *(action_client_.getResult());  // checking the result
       std::this_thread::sleep_for(std::chrono::milliseconds(10));
 }
 while (node_result.status == BT::RUNNING && get_status() != BT::HALTED);
```

**Comment by miccol** [comment]
HI fnivek,

thank you for spotting this!

Fixed in commit [8e30663](https://github.com/miccol/ROS-Behavior-Tree/commit/8e306632aa91121e9546689d20eb79c903d43e52)
