### ISSUE TITLE
Enquiry about new action

### ISSUE THREAD

**Issue by detectiveli** [miccol/ROS-Behavior-Tree#18]
Hello, I would like to build a new self-defined action class. But if I copy the action_example.cpp and rename the class, I still need to rewrite the ros_action.cpp and ros_action.h to use the external_ros_nodes_test.cpp. Is there any other way to create a new action? Thanks!

**Comment by miccol** [comment]
Hello,

Thank you for using the library.

I am assuming that you want to create an **external** BT node (running on a separate ROS node). 
You just need to copy `action_example.cpp` and rename it, you don't need to do anything else. Remember to give a name to the  ROS node in line 106 (just change `action` into the name you want.)  

https://github.com/miccol/ROS-Behavior-Tree/blob/0e33bd35eb3e8446783672665ea175b53ee9f9dd/behavior_tree_leaves/example_nodes/cpp/action_example.cpp#L106


Then when you call the external BT node from your BT core node (the one running the BT engine) create the object  ROSAction(`namechosen`) and add it to the tree.


Let me know if this fixes your issue.

Cheers
MC

**Comment by detectiveli** [comment]
Thanks for replying so fast!

Yes, it works! And I do fit something else like CMakeLists.txt and test_behavior_tree.launch to start the nodes.

Many thanks to your contribution again!

**Comment by miccol** [comment]
You're welcome.
Please star the library if you like it.

If you have further questions or doubts, open an issue.
Cheers
MC
