### ISSUE TITLE
Package does not compile with catkin_tools (catkin build)

### ISSUE THREAD

**Issue by piraka9011** [miccol/ROS-Behavior-Tree#19]
I've been working with this package for a while now and its been great so far. It compiles with catkin_make with the following warnings (which I'm not sure are important?):
```
CMake Warning (dev) at CMakeLists.txt:73 (add_dependencies):
  Policy CMP0046 is not set: Error on non-existent dependency in
  add_dependencies.  Run "cmake --help-policy CMP0046" for policy details.
  Use the cmake_policy command to set the policy and suppress this warning.

  The dependency target "frasier_behavior_generate_messages_cpp" of target
  "spr_conditions" does not exist.
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at CMakeLists.txt:62 (add_dependencies):
  Policy CMP0046 is not set: Error on non-existent dependency in
  add_dependencies.  Run "cmake --help-policy CMP0046" for policy details.
  Use the cmake_policy command to set the policy and suppress this warning.

  The dependency target "frasier_behavior_generate_messages_cpp" of target
  "spr_bt" does not exist.
This warning is for project developers.  Use -Wno-dev to suppress it.
```

My issue though is that my team uses catkin_tools to build our packages and I'd like to have the same build environment they have. Apparently the linker cannot find the `behavior_tree_core` library.
```
/usr/bin/ld: cannot find -lbehavior_tree_core
collect2: error: ld returned 1 exit status
```
I tried making `behavior_tree_core` into a library by changing the `CMakeLists.txt` but it didn't work:
```
catkin_package(
  CATKIN_DEPENDS actionlib_msgs
  LIBRARIES behavior_tree_core <-- Added this line
  INCLUDE_DIRS include
)
```
This is how I link the libraries in my other package:
```
add_executable(spr_bt src/spr_bt.cpp)
target_link_libraries(spr_bt
        ${catkin_LIBRARIES}
        behavior_tree_core
        )
add_dependencies(spr_bt
        ${catkin_EXPORTED_TARGETS}
        ${PROJECT_NAME}_generate_messages_cpp
        behavior_tree_core_generate_messages_cpp
        )
```
And my `find_package`:
```
find_package(catkin REQUIRED COMPONENTS
  actionlib_msgs
  actionlib
  behavior_tree_core
  behavior_tree_leaves
  genmsg
  message_generation
  roscpp
  rospy
  roslib
  geometry_msgs
)
```
Any suggestions on how to get this working with catkin_tools?

**Comment by miccol** [comment]
Hi,
Thank you for using the library.

The warnings are due to CMake and they will be removed eventually (https://github.com/ros/catkin/issues/796).

I just tried to compile with catkin build and it seemed to work.
I suspect that you are running `catkin build` in the same workspace that you compile with `catkin_make`(in that case it cannot work as the generated files are different). If that is the case, can you try to run catking build in a new workspace (initialized with `catkin init` and not `catkin_initialize_workspace`) and get back to me? 
Another option is to run `catkin clean` clean first but I suggest to avoid having to swtich back and forth, unless necessary. 


Regards
MC

**Comment by piraka9011** [comment]
A made a clean workspace initialized with `catkin init`. It has 2 packages only, the `ROS-Behavior-Tree` and my other package using the behavior tree `frasier_behavior`. `frasier_behavior` still returns the same error as above: 
```
/usr/bin/ld: cannot find -lbehavior_tree_core
collect2: error: ld returned 1 exit status
```
Here is `frasier_behavior`'s CMakeLists:
```
cmake_minimum_required(VERSION 2.8.3)
project(frasier_behavior)

add_compile_options(-std=c++11)
add_definitions(-Wall -Wno-deprecated -Wno-dev -static -Bstatic -std=gnu++0x)

find_package(catkin REQUIRED COMPONENTS
  actionlib_msgs
  actionlib
  behavior_tree_core
  behavior_tree_leaves
  genmsg
  message_generation
  roscpp
  rospy
  roslib
  geometry_msgs
)
catkin_package(
   CATKIN_DEPENDS roscpp rospy behavior_tree_leaves behavior_tree_core message_runtime
)

###########
## Build ##
###########
include_directories(
  include
  ${catkin_INCLUDE_DIRS}
)

# Main BT Node
add_executable(spr_bt src/spr_bt.cpp)
target_link_libraries(spr_bt
        ${catkin_LIBRARIES}
        behavior_tree_core
        )
add_dependencies(spr_bt
        ${catkin_EXPORTED_TARGETS}
        ${PROJECT_NAME}_generate_messages_cpp
        behavior_tree_core_generate_messages_cpp
        )

```

**Comment by miccol** [comment]
could it be that you are missing a dependency in your package.xml (in `frasier_behavior`)?

**Comment by piraka9011** [comment]
I don't think so. Below is my `package.xml`:
```
  <buildtool_depend>catkin</buildtool_depend>

  <build_depend>actionlib</build_depend>
  <build_depend>actionlib_msgs</build_depend>
  <build_depend>behavior_tree_core</build_depend>
  <build_depend>behavior_tree_leaves</build_depend>  
  <build_depend>genmsg</build_depend>
  <build_depend>geometry_msgs</build_depend>
  <build_depend>message_generation</build_depend>
  <build_depend>roscpp</build_depend>
  <build_depend>rospy</build_depend>

  
  <run_depend>actionlib</run_depend>
  <run_depend>actionlib_msgs</run_depend>
  <run_depend>behavior_tree_core</run_depend>
  <run_depend>behavior_tree_leaves</run_depend>
  <run_depend>genmsg</run_depend>
  <run_depend>geometry_msgs</run_depend>
  <run_depend>message_runtime</run_depend>
  <run_depend>roscpp</run_depend>
  <run_depend>rospy</run_depend>

```

Double checked and still have the same error unfortunately.

**Comment by miccol** [comment]
could it be related to this: https://answers.ros.org/question/9338/cannot-find-libraries-when-linking/

**Comment by piraka9011** [comment]
Add the following to my CMake: `link_directories(${CATKIN_DEVEL_PREFIX}/lib)`
Still didn't fix the issue (although I do see a `libbehavior_tree_core.so` file in there!)
Could this be an issue where behavior tree core package is not compiled as a library but rather just as certain executables?

**Comment by miccol** [comment]
I never used catkin build so I am not sure where the problem could be but we can work together to fix it.

try to change

```
target_link_libraries(spr_bt
        ${catkin_LIBRARIES}
        behavior_tree_core
        )

```
to 

```
target_link_libraries(spr_bt
        ${catkin_LIBRARIES}
        ${behavior_tree_core_LIBRARIES}
        )
```

**Comment by piraka9011** [comment]
Solved it by changing `catkin_package()` in `behavior_tree_core`'s CMakeLists.txt to:
```
catkin_package(
  CATKIN_DEPENDS actionlib_msgs
  INCLUDE_DIRS include
  LIBRARIES ${PROJECT_NAME}    # Added this line
)
```
Compiled with `catkin_make` and `catkin build`. Executables do run. Did not have to change `target_link_libraries()`. This is what I have currently:
```
target_link_libraries(spr_bt
  ${catkin_LIBRARIES}
)
```
If I add `behavior_tree_core` it does not compile, if I add `${behavior_tree_core_LIBRARIES}` it compiles. See #21

**Comment by miccol** [comment]
great!
