### ISSUE TITLE
behavior_tree

### ISSUE THREAD

**Issue by ewerlopes** [miccol/ROS-Behavior-Tree#2]
Hi again...

It seems the folder `behavior_tree` is sitting there doing nothing really useful. Am I overlooking it or does it have a full purpose for the rest of the code? Your new README doesn't even mention it... 

Thanks, sorry for any trouble.

**Comment by miccol** [comment]
no troubles at all.
Before starting, please re-clone the library if you are using ROS hydro. They removed the dependency of `genmsg` from `actionlib` and I had to include explicitly such dependency.  I have tested it now in a fresh installation of Ubuntu 14.04 with Hydro.

the folder `behavior_tree` is a metapackage. It is used to identify with packages must be compiled. In the file package.xml there is:

  <buildtool_depend>catkin</buildtool_depend>
  <run_depend>behavior_tree_core</run_depend>
  <run_depend>behavior_tree_leaves</run_depend>

this means that when you run: `catktin_make behavior_tree`, catkin compiles (if necessary)  behavior_tree_core and behavior_tree_leaves. So you avoid to run different catkin_make commands.

 More info on metapackages here: http://wiki.ros.org/Metapackages

**Comment by ewerlopes** [comment]
Okay. I will check on it.
I am using Indigo.

Thanks.
