### ISSUE TITLE
full example with external ROS nodes?

### ISSUE THREAD

**Issue by dan9thsense** [miccol/ROS-Behavior-Tree#22]
Thank you for writing this library; it looks very useful for my project.  I have the examples running well.
However, I was having difficulty understanding how to create and use external ROS nodes.  

Details edited out, as they were answered when I found the example nodes.

**Comment by dan9thsense** [comment]
Looking at external_ros_nodes_test.cpp and action_example.cpp answered the questions and I am now able to make it all work.

**Comment by miccol** [comment]
great! Let me know if you have further comments.

**Comment by varunvp** [comment]
I see that ros_action.cpp depends on action_example.cpp. Can the contents of action_example be shifted to ros_action node?
