### ISSUE TITLE
Looking for ROS2 port

### ISSUE THREAD

**Issue by mhpanah** [miccol/ROS-Behavior-Tree#24]
Hi, I would like to use the Behavior-Tree for ROS2 and I was wondering if this library has been ported to ROS2 or if there is any plan for porting it to ROS2?

Thank you,

Mohammad

**Comment by miccol** [comment]
Hi Mohammad,

yes, I will eventually port this to ROS2. Unfortunately, I am quite busy this period on other matters. I hope I can get back to this soon.

Regards
MC
