### ISSUE TITLE
BT node display overlap problem

### ISSUE THREAD

**Issue by xiaofyao** [miccol/ROS-Behavior-Tree#26]
when I ran the BT program, there was an displays overlap problem:

![image](https://user-images.githubusercontent.com/37805843/47546697-feb31780-d924-11e8-8a01-a11ef82e3696.png)

Could someone help me solve the problem?

**Comment by miccol** [comment]
Hi, To increase/decrease the space between the node, use the PageUp/PageDown buttons.
Take a look also at the new version of the library here: 

https://github.com/BehaviorTree/BehaviorTree.CPP
