### ISSUE TITLE
Problem of passing parameters to leaf node and repeated mount of leaf nodes

### ISSUE THREAD

**Issue by xiaofyao** [miccol/ROS-Behavior-Tree#27]
Hi,

Dear developers, When I used this open source project, I found these problems:

1.   The software design does not support passing parameters to leaf node.

2.    A leaf node is not allowed to mount repeatedly to the same control node.

Do you think these two problems need optimization?

Best Regards,
Yao Xiaofan

**Comment by miccol** [comment]
Hi, this version is a lightweight. Take a look at the new one for parameter passing. 

https://github.com/BehaviorTree/BehaviorTree.CPP
