### ISSUE TITLE
Pros and Cons for ROS-Behavior-Tree

### ISSUE THREAD

**Issue by krixkrix** [miccol/ROS-Behavior-Tree#28]
Is ROS-Behavior-Tree actively maintained?
Is ROS-Behavior-Tree considered mature and usable for production code?
I notice that @miccol is contributing to [BehaviorTree.CPP](https://github.com/BehaviorTree/BehaviorTree.CPP) as well. Is this a better choice or what is the Pros and Cons for one implementation versus the other?

Basically I am looking for a replacement for a ROS SMACH-based sequencing engine, which suffers from being slow and vulnerable to threading issues. Maybe the answers to my above questions would be nice to have in the [README](https://github.com/miccol/ROS-Behavior-Tree/blob/master/README.md)

Are the people behind ROS-Behavior-Tree actively following [ROS answers](https://answers.ros.org/questions/) so questions can be asked there instead of in an issue like this?

**Comment by miccol** [comment]
Hi, yes this library is no longer maintained, use [BehaviorTree.CPP](https://github.com/BehaviorTree/BehaviorTree.CPP) instead. Due to legacy code on some projects (and related installation instructions that require this library), I will keep this library online. 

Thank you!
