### ISSUE TITLE
Add more action on the  sequnce node

### ISSUE THREAD

**Issue by LMNcnu** [miccol/ROS-Behavior-Tree#3]
The third action node will not execute when adding three action node on the sequence node. Why?

**Comment by miccol** [comment]
A sequence node, at every tick, it ticks its first child. If the first child return success, it ticks the second and so on. This is the key feature if you want you have reactiveness (e.g. you perform Action 1 and then Action 2 and, while performing Action 2, the result of Action 1 is no longer valid. Then you want to re-perform Action 1). If you want to have a strict sequence of action the use the SequenceStarNode class.

If you have further problems, feel free to contact me again.

Michele.

**Comment by LMNcnu** [comment]
Thanks, I have solved my problem using the SequenceStarNode class.
