### ISSUE TITLE
Sequence with memory: Return to first Child node by Failure

### ISSUE THREAD

**Issue by resmaessen** [miccol/ROS-Behavior-Tree#30]
Hi!

I'm using the sequence with memory node. And I was wondering if it is possible to start at the first child of a sequence node when one of the other child nodes (so not the first one) returns as FAILURE. 

Kind regards,

Rosa

**Comment by miccol** [comment]
This is how it should behave. Can you share your code?

**Comment by resmaessen** [comment]
This is the Behavior Tree code: 

```
#include <behavior_tree.h>
int main(int argc, char **argv)
{
    ros::init(argc, argv, "BehaviorTree");
    try
    {
        int TickPeriod_milliseconds = 1000;

        BT::ParallelNode* parallel1 = new BT::ParallelNode("parallel",2);
        BT::SequenceNodeWithMemory* sequence1 = new BT::SequenceNodeWithMemory("seq1");

        BT::ActionNodeF1* F1 = new BT::ActionNodeF1("F1");
        BT::SequenceNodeWithMemory* sequence2 = new BT::SequenceNodeWithMemory("seq2");

        BT::ActionNodeF4* F2 = new BT::ActionNodeF4("F2");

        BT::SequenceNodeWithMemory* sequence3 = new BT::SequenceNodeWithMemory("seq3",4);

        BT::ActionNodeF5* F5 = new BT::ActionNodeF5("F5");
        BT::ActionNodeF6* F6 = new BT::ActionNodeF6("F6");
        BT::ActionNodeF7* F7 = new BT::ActionNodeF7("F7");
        BT::ActionNodeF7_1b* F7_1b = new BT::ActionNodeF7_1b("F7_1b");

        BT::ConditionNodeF7_1* F7_con  = new BT::ConditionNodeF7_1("F7_con");

        // Linking

        parallel1->AddChild(sequence1);
        parallel1->AddChild(F7);

        sequence1->AddChild(F1);
        sequence1->AddChild(sequence3);

        sequence3->AddChild(F7_1b);
        sequence3->AddChild(F6);
        sequence3->AddChild(F5);
        sequence3->AddChild(F7_con);

        Execute(parallel1, TickPeriod_milliseconds);  // from BehaviorTree.cpp
    }
    catch (BT::BehaviorTreeException& Exception)
    {
        std::cout << Exception.what() << std::endl;
    }
    return 0;
}
```
The aciton and condition nodes work fine indivually. However when ticking the last leafnode (the F7_con condition node), it will tick it and when it returns failure it will restart the tree from the parallel node. 

I hope you can help me! If you need to see other files, please let me know!

**Comment by miccol** [comment]
I guess the problem is with `sequence3`

The second argument of `SequenceNodeWithMemory` is this enum ON_SUCCESS_OR_FAILURE, ON_SUCCESS, ON_FAILURE
hence try change this:

`BT::SequenceNodeWithMemory* sequence3 = new BT::SequenceNodeWithMemory("seq3",4);`

to

`BT::SequenceNodeWithMemory* sequence3 = new BT::SequenceNodeWithMemory("seq3",BT::ON_FAILURE);`
