### ISSUE TITLE
Action and condition templates use wrong namespace for the action servers template class

### ISSUE THREAD

**Issue by diogoalmeida** [miccol/ROS-Behavior-Tree#4]
You have a residual 'amazon_challenge_behavior_tree_leaves' namespace on the templates provided in the 'behavior_tree_leaves' package.

You can find the lines [here](https://github.com/miccol/ROS-Behavior-Tree/blob/e27b2315a4db569e23de7677478fe9938a682271/behavior_tree_leaves/src/ActionTemplate.cpp#L16) and [here](https://github.com/miccol/ROS-Behavior-Tree/blob/e27b2315a4db569e23de7677478fe9938a682271/behavior_tree_leaves/src/ConditionTemplate.cpp#L17)

**Comment by miccol** [comment]
Thanks! I will fix that

**Comment by diogoalmeida** [comment]
BTW I also believe that the namespace 'behavior_tree_leaves' used, for instance [here](https://github.com/miccol/ROS-Behavior-Tree/blob/e27b2315a4db569e23de7677478fe9938a682271/behavior_tree_leaves/src/ConditionTemplate.cpp#L20), should be 'behavior_tree_core', as you do in the Action and Condition examples.

**Comment by miccol** [comment]
Thanks, never realized that as it is this file is not compiled

**Comment by diogoalmeida** [comment]
Yeah, I just realized it now that I used the templates myself :)

**Comment by davidalbertonogueira** [comment]
Nice observations Diogo.
