### ISSUE TITLE
Prebuilt binary packages

### ISSUE THREAD

**Issue by AravindaDP** [miccol/ROS-Behavior-Tree#6]
Hi
Do you have any plans to release this as a pre built catkin package on ros buildfarm for indigo and above? (So it's possible to install as binary opposed to building from source)
Thanks in advance.

**Comment by miccol** [comment]
Hi,

Yes! as from March 7, the day I will submit my PhD thesis, I will work on the new version of the library. I will also release a pre-built catkin package.

Thank you for using the library.

Michele

**Comment by AravindaDP** [comment]
Thanks for your response and Good luck with your studies.

Great to hear that your plans on developing the library. I also have couple of more functionalities to suggest (Will open in a new issue to discuss them)

While I'm also bit novel to ROS feel free to contact me if I could be of any help.

Closing this issue for now.

**Comment by miccol** [comment]
Hi,

have a look at the library now.
the feature you have requested is probably included now.

If you like the library, please star it!

Thanks
MC
